server:
  port:
    8081

audio:
  music:
    #    folderpath: 'C:\Users\choud\Downloads'
    folderpath: 'C:\Users\choud\Downloads\Top 50 Single Track'
    baseUrl: 'http://100.125.57.120:${server.port}'
